In [1]:
# Importing the library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

dataset = pd.read_csv('Datasets/Data.csv')
X = dataset.iloc[:,1:2].values # To get the features as a matrix instead of a vector
y = dataset.iloc[:,2].values

"""
# Splitting the dataset into training set and the test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.20, random_state=0)
"""

"""
Feature scaling

from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

"""



'\nFeature scaling\n\nfrom sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nsc_y = StandardScaler()\nX = sc_X.fit_transform(X)\ny = sc_y.fit_transform(y)\n\n'

In [2]:
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [3]:
#iloc allows us to take caloumns just by taking their index
#iloc[<rowindex>,<columnindex>]
# all columns except the last column
#dataset.iloc[:,:-1] 
#dataset.iloc[:,:-2] except last 2

# Get only the last column

dataset.iloc[:,3] #: -> all 



0     No
1    Yes
2     No
3     No
4    Yes
5    Yes
6     No
7    Yes
8     No
9    Yes
Name: Purchased, dtype: object

In [4]:
#  -> converts to numpy arrays -> used for ML models
dataset.iloc[:,3].values

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [5]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values

In [6]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [7]:
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [23]:
# Taking care of missing data (by replacing NaNs with mean)

from sklearn.preprocessing import Imputer
# Create a object from the Imputer class

imputer = Imputer(missing_values='NaN',strategy='mean', axis=0) #replace NaNs with mean

# Fit the imputer for X and select the columns that have NaNs

imputer = imputer.fit(X[:,1:3])

# Replace the NaNs in X using the transform method of the imputer object

X[:,1:3] = imputer.transform(X[:,1:3])




/usr/local/lib/python3.7/site-packages/sklearn/utils/deprecation.py:58: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [24]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [28]:
# Using simpleimputer
import numpy as np
# Taking care of missing data

from sklearn.impute import SimpleImputer
# Create a object from the Imputer class

simputer = SimpleImputer(missing_values=np.nan,strategy='mean') #replace NaNs with mean

# Fit the imputer for X and select the columns that have NaNs

simputer = simputer.fit(X[:,1:3])

# Replace the NaNs in X using the transform method of the imputer object

X[:,1:3] = simputer.transform(X[:,1:3])

In [29]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [33]:
# Encoding categorical variables
# We have country and purchased as the categorical variables

from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()

X[:,0]=labelencoder_X.fit_transform(X[:,0])

In [34]:
X

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [35]:
# The above method has a problem since the ML model can attribute on order and ML can think 0 < 1 <2
# We can solve this by using dummy columns one dummy column for each category = 3 

from sklearn.preprocessing import OneHotEncoder
onehotencoder=OneHotEncoder(categorical_features=[0])
X=onehotencoder.fit_transform(X).toarray()



/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.7/site-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [36]:
X

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [37]:
# Use encoding for the purchased column
# Since this is a dependent variable, ML knows that there is no order so we can get away using the label encoder

labelencoder_y = LabelEncoder()
y=labelencoder_y.fit_transform(y)

In [38]:
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [43]:
# Splitting the dataset into training set and the test set

# from sklearn.cross_validation import train_test_split 
# by
# from sklearn.model_selection import train_test_split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.20, random_state=0)


In [45]:
len(X_test)

2

In [49]:
# Feature scaling ( no variable is dominated by the other)
# euclidean distance
# standardization or normalization
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
# Fit and transform the training set
X_train = sc_X.fit_transform(X_train)
#Only transform the test set
X_test = sc_X.transform(X_test)
# Question for us, do we need to scale or dummy variables? Depends if we want to interpret 
# Do we need to apply feature scaling for the dependent variable (y)? Not in this case as it is a categorical variable. We will need to do it if it was a wide range of values

In [51]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.45882927, -0.90166297],
       [-1.        ,  2.64575131, -0.77459667,  1.98496442,  2.13981082]])

In [53]:
###############################
# Data preprocessing template #
###############################

# Importing the library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Importing the dataset

dataset = pd.read_csv('Datasets/Data.csv')
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3].values


# Splitting the dataset into training set and the test set
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.20, random_state=0)

# Feature scaling ( no variable is dominated by the other)
from sklearn.preprocessing import StandardScaler
sc_X=StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)